name: cholec80_phase_planning
data: SurgicalPhasePlanning
data_config:
  transform: None
  data_dir: /home/ubuntu/datasets/vlm/Cholec80
  vqa_path: /home/ubuntu/datasets/vlm/Cholec80-VQA-Planning/phase_planning.json
  frame_template: "{data_dir}/frames_25fps/test/{video_id}/{frame}.jpg"
n_context: 16
stride: 25
label_names: ['current_phase', 'next_phase']
clip_eval_mode: 'singlelabel'
shots: zero
