# Task
name: heichole_phase_recognition_fewshot
data: HeiCholeDataloader
data_config:
  transform: None
  data_dir: /home/ubuntu/datasets/vlm/HeiCo
label_names: ['Preparation', 'Calot Triangle Dissection', 'Clipping & Cutting', 'Gallbladder Dissection', 'Gallbladder Packaging', 'Cleaning & Coagulation', 'Gallbladder Retraction']
clip_eval_mode: 'singlelabel'  # single label multi-class classification
shots: one
