# Task
name: heichole_action_recognition_fewshot
data: HeiCholeDataloader
data_config:
  transform: None
  data_dir: /Users/boseong/dataset/HeiChole
label_names: ['grasp', 'hold', 'cut', 'clip']
shots: one
